version: "3"
services:
  qemu:
    container_name: qemu
    image: qemux/qemu-docker
    environment:
      BOOT: "http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/netboot/mini.iso"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "128G"
      BOOT_MODE: "uefi"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - D:\Qemu_OS:/storage